### ISSUE TITLE
jQuery(...).filedrop is not a function with jQuery 3.1.1

### ISSUE THREAD

**Issue by jmchauv** [weixiyen/jquery-filedrop#185]
Is there a fix for this? I am upgrading from jQuery 1.7.2 to 3.1.1 and am receiving this error:

`jQuery(...).filedrop is not a function`

**Comment by Dolgovec** [comment]
Found that problem too. The solution is:
1) remove jQuery.event.props.push("dataTransfer");
2) change e.dataTransfer to e.originalEvent.dataTransfer

good luck

upd: fixed in new file version already (v. is still 0.1.0)

**Comment by rickdatel** [comment]
I am having the same issue with jQuery 3.2.1 have tried to the fix above but its causing other

**Comment by mvpkenlin** [comment]
I am also having the same issue with JQuery 3.2.1. 
Tried the above fix, but now it generate another error "Syntax error, unrecognized expression: #"

**Comment by ShawnJ013** [comment]
Hello I've tried this fix above as well, does any one have an update, I've been searching for a couple hours now, I'm working on a MVC 5, jquery-3.3.1 project, and I like the FileDrop.js function for its simplicity.

**Comment by alexd612** [comment]
Using JQuery 3.3.1 and tried the fix above and get 

 "Syntax error, unrecognized expression: #"

Any ideas?

**Comment by carlblanchard** [comment]
Add this reference then all will become good in the world....
`<script src="https://code.jquery.com/jquery-migrate-3.0.1.js"></script>`

**Comment by allac00** [comment]
im also facing this issue. 
The solution 
"* remove jQuery.event.props.push("dataTransfer");
* change e.dataTransfer to e.originalEvent.dataTransfer"

also gives the next error: "Syntax error, unrecognized expression: #".

Adding the reference to jquery-migrate doesnt solve it either. 

Please advise.

**Comment by alexd612** [comment]
Hey i think i ended up just using a file browse button. I could never get
the drop box working properly.

**Comment by joshuafredrickson** [comment]
#186 fixes this issue if you're in a pinch.

**Comment by Nailuj2k** [comment]
Hi, i have made a fork and submit a pull request with solution to this error.
The error is when opt fallback_id is not set, then in filedrop.js the line 100 fail because $('#') is not a valid identifier
Solutions is move these block into " if ( opts.fallback_dropzoneClick === true )"
or setting the option 'fallback_id' to any existing element
or simply check if fallback_id is set 

:)
